### ISSUE TITLE
quick spelling error!

### ISSUE THREAD

**Issue by evanvin** [dride/dride-website#40]
So excited for the release of more documentation so I can sit down one weekend and make this. I noticed a small spelling error on your website. 

In main.component.html:
`<h3 class="slogen mx-auto">Dont guess how pepole drive your cars.</h3>`

"people" was just spelled wrong. As a fellow programmer I have made this quick typing mistake multiple times.

**Comment by saoron** [comment]
Thanks you for this catch 😲  & welcome to the community!
